name: Test and release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: taiki-e/install-action@cargo-binstall
      - run: cargo binstall --no-confirm --force cargo-edit
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REL }}
      - run: just release
        env:
          GITHUB_TOKEN: ${{ secrets.REL }}
